#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -r n
#PBS -j oe
#PBS -q workq
#PBS -l walltime=48:00:00
#PBS -N run-$i
# EVERYTHING ABOVE THIS COMMENT IS NECESSARY, SHOULD ONLY CHANGE nodes,ppn,walltime and my_job_name VALUES

# example for submitting to sunnyvale:
# qsub -v filename="system-5629353-0.bin",inttype="year",i=440 sunnyvale-qsub-script
cd $PBS_O_WORKDIR
module load gcc/7.3.0
source /mnt/raid-cita/obertas/opt/python/venv-3.6.4-aug-2020/bin/activate
export PYTHONUSERBASE=/mnt/raid-cita/obertas/.local
export PYTHONPATH=/mnt/raid-cita/obertas/.local/lib/python3.6.4/site-packages:$PYTHONPATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/python/3.6.4/lib
python run_system.py $filename $inttype
