#!/bin/bash

iter=0

# for f in integrated-simulation-archives/1e9-orbits/*
# for f in earth-mass-archives/integrated-archives/1e9-orbits/*
for f in non-zero-inc-archives/integrated-archives/*
do
    qsub -v filename=$f,i=$iter sunnyvale-qsub-script
    ((iter++))
done
