#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -r n
#PBS -j oe
#PBS -q workq
#PBS -l walltime=48:00:00
# EVERYTHING ABOVE THIS COMMENT IS NECESSARY, SHOULD ONLY CHANGE nodes,ppn,walltime and my_job_name VALUES

# example for submitting to sunnyvale:
# qsub -v sysid=12154526,place=0,dirname="spock-probs/",n_samp=10 sunnyvale-qsub-script-spock-probs
cd $PBS_O_WORKDIR
module load python/3.10.2
source /mnt/raid-cita/obertas/venv-apr-2023-3.10.2/bin/activate
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/cita/modules/python/3.10.2/lib
python calc-spock-probs-new.py $sysid $place $dirname $n_samp
